{{- if and .Values.secrets.create (not .Values.secrets.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fides.fullname" . }}-secrets
  labels:
    {{- include "fides.labels" . | nindent 4 }}
type: Opaque
stringData:
  db-dsn: {{ include "fides.appDSN" . | quote }}
  postgres-password: {{ .Values.database.ownerPassword | quote }}
  owner-dsn: "host={{ .Values.database.host }} port={{ .Values.database.port }} user={{ .Values.database.ownerUser }} password={{ .Values.database.ownerPassword }} dbname={{ .Values.database.name }} sslmode={{ .Values.database.sslmode }}"
  encryption-key: {{ .Values.secrets.encryptionKey | quote }}
  api-token: {{ .Values.secrets.apiToken | quote }}
  portal-password: {{ .Values.portal.password | quote }}
{{- end }}
